### ISSUE TITLE
直接传字符串播报不依赖网页元素可以实现么

### ISSUE THREAD

**Issue by QQ897878763** [wenco/speech#1]
$('#Result').speech({
		"speech": true,
		"speed": 1,
		"bg": "./images/speech.png"
	});
	
我想直接就传context 不用绑定元素

**Comment by QQ897878763** [comment]
可以这么写 

	$(function(){
	  speckText('您有新的订单啦~')
	});
 
	 function speckText(str){ 
        var url = "http://tts.baidu.com/text2audio?lan=zh&ie=UTF-8&text=" + encodeURI(str);
        　　var n = new Audio(url);
       　　 n.src = url;
       　　 n.play();
    }

**Comment by wenco** [comment]
这使用的是baidu的tts接口，必须要有网络。或者你有什么更好的方式，比如接入手机系统的语音朗读。
你这个直接调用在特定场合下很实用，感谢你的反馈。
